#:set xx 368
#:set yy 286

<AboutPage>:
	BoxLayout:
		orientation: 'vertical'
		MyActionBar:
			title:"About"
			to_page:"LandingPage"

		Widget
		Label:
			canvas:
				Rectangle:
					id:rect
					source: 'pics/logo_minimal.png'
					# pos: (20,self.pos[1]+20)
					pos:(self.parent.size[0]//2-xx//2,self.parent.size[1]//2)
					# pos:(self.parent.size[0]//2-size_x//2,self.parent.size[1]//2+size_y//2)
					size: (xx,yy)